name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Lint
        run: pnpm run lint

  test-app:
    name: Test app
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Test
        uses: percy/exec-action@v0.3.1
        with:
          custom-command: pnpm run test:ember
        env:
          PERCY_TOKEN: 877df6aad8486060f69a34864b6cd33f870633743b23411343737c46a875a762

  test-node:
    name: Test node-tests
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Test
        run: pnpm run test:node
